const ProductDetail = [
    {
        id:1,
        title:"Samsung Galaxy Tab S6 Lite (SM-P619) 128 GB Blue.",
        cap:"Tablet",
        price:"465",
        img:"./img/hpp1.png",
    },
    // {
    //     id:2,
    //     title:"HUAWEI Watch Fit 2 Classic Moon White.",
    //     cap:"Smart Watch",
    //     price:"$72",
    //     img:"./img/hpp2.png",
    // },
    // {
    //     id:3,
    //     title:"Cancelling Headphones Wireless.",
    //     cap:"Headphone",
    //     price:"$120",
    //     img:"./img/hp3.png",
    // },
    // {
    //     id:4,
    //     title:"Professional Camera 4K Digital Video Camera.",
    //     cap:"HD Camera",
    //     price:"$340",
    //     img:"./img/hp4.png",
    // },
    // {
    //     id:5,
    //     title:"Mini Portable PD 22.5W Fast Charging Powerbank.",
    //     cap:"Powerbank",
    //     price:"$72",
    //     img:"./img/hp5.png",
    // },
    // {
    //     id:6,
    //     title:"CPU Cooler 2 Heat Pipes 12mm 4 Pin PWM RGB for Intel.",
    //     cap:"Heat Pipes",
    //     price:"$133",
    //     img:"./img/hp6.png",
    // },
    // {
    //     id:7,
    //     title:"Playstation 4 2TB Slim Gaming Console.",
    //     cap:"Gaming",
    //     price:"$142",
    //     img:"./img/hp7.png",
    // },
    // {
    //     id:8,
    //     title:"Mini Portable Mobile Phone Powerbank for iphone.",
    //     cap:"Backpacks",
    //     price:"$97",
    //     img:"./img/hp8.png",
    // },
    {
        id:9,
        title:"Apple Watch SE 44 mm Midnight Aluminium.",
        cap:"Smart Watch",
        price:"420",
        img:"./img/hp9.png",
    },
    {
        id:10,
        title:"Headphone SBS ON EAR/red.",
        cap:"Headphone",
        price:"39",
        img:"./img/hp10.png",
    },
    {
        id:11,
        title:"OPPO Reno 8T 8/128 GB Orange.",
        cap:"Phone",
        price:"465",
        img:"./img/hp11.png",
    },
    {
        id:12,
        title:"PS5 DualSense Galactic Purple.",
        cap:"Gaming",
        price:"78",
        img:"./img/hp12.png",
    },
    {
        id:13,
        title:"Samsung Galaxy Tab A8 LTE 64GB (SM-X205) Gray.",
        cap:"Tablet",
        price:"471",
        img:"./img/hp13.png",
    },
    {
        id:14,
        title:"Apple MagSafe Battery Pack MJWY3ZM/A.",
        cap:"Powerbank",
        price:"112",
        img:"./img/hp14.png",
    },
    {
        id:15,
        title:"HUAWEI Band 7 Nebula Pink.",
        cap:"Smart Watch",
        price:"59",
        img:"./img/hp15.png",
    },
    {
        id:16,
        title:"Nillkin iPhone 14 Pro Max Nature MagSafe White - 8632.",
        cap:"Backpacks",
        price:"16",
        img:"./img/hp16.png",
    },
    {
        id:17,
        title:"iPad Pro 11-İnch (4Th Gen) Wi-Fi 512 GB - Silver.",
        cap:"Tablet",
        price:"799",
        img:"./img/hp17.png",
    },
    {
        id:18,
        title:"PlayStation VR2.",
        cap:"Gaming",
        price:"536",
        img:"./img/hp18.png",
    },
    {
        id:19,
        title:"Defunc True Sport D4332 White.",
        cap:"Headphone",
        price:"115",
        img:"./img/hp19.png",
    },
    {
        id:20,
        title:"iPhone 14 Pro 128 GB Deep Purple.",
        cap:"Phone",
        price:"999",
        img:"./img/hp20.png",
    },
    {
        id:21,
        title:"Samsung Watch 4 46 mm Classic Black (SM-R890NZKACIS).",
        cap:"Smart Watch",
        price:"399",
        img:"./img/hp21.png",
    },
    {
        id:22,
        title:"Power Bank Joyroom 10000 mAh / JR-L002.",
        cap:"Powerbank",
        price:"25",
        img:"./img/hp22.png",
    },
    {
        id:23,
        title:"Xiaomi Poco X5 Pro 5G 8/256 GB Black.",
        cap:"Phone",
        price:"499",
        img:"./img/hp23.png",
    },
    {
        id:24,
        title:"Ps Move Twin Pack.",
        cap:"Gaming",
        price:"91",
        img:"./img/hp24.png",
    },
    {
        id:25,
        title:"Blackview R3 Pink Smartwatch.",
        cap:"Smart Watch",
        price:"42",
        img:"./img/hp25.png",
    },
    {
        id:26,
        title:"Samsung Galaxy A24 (SM-A245) 6/128 GB Silver.",
        cap:"Phone",
        price:"388",
        img:"./img/hp26.png",
    },
    {
        id:27,
        title:"Apple Watch 7 41 mm Red MKN23.",
        cap:"Smart Watch",
        price:"462",
        img:"./img/hp27.png",
    },
    {
        id:28,
        title:"Xbox Series X 1 TB.",
        cap:"Gaming",
        price:"809",
        img:"./img/hp28.png",
    },
]
export default ProductDetail;